databases:
  - name: matrixmatch-db
    plan: free
    postgresMajorVersion: "16"
    databaseName: matrixmatch
    user: matrixmatch

services:
  - type: web
    name: matrixmatch
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DB_HOST
        fromDatabase:
          name: matrixmatch-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: matrixmatch-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: matrixmatch-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: matrixmatch-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: matrixmatch-db
          property: database
      - key: DB_OPTIONS
        value: -c search_path=matrixmatch,public
